### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by freddygenicho** [laravel-notification-channels/trello#11]
Problem 1
    - Installation request for laravel-notification-channels/trello ^1.0 -> satisfiable by laravel-notification-channels/trello[1.0.0].
    - Conclusion: remove laravel/framework v5.6.27
    - Conclusion: don't install laravel/framework v5.6.27
    - laravel-notification-channels/trello 1.0.0 requires illuminate/notifications 5.3.* -> satisfiable by illuminate/notifications[5.3.x-dev, v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - don't install illuminate/notifications 5.3.x-dev|don't install laravel/framework v5.6.27
    - don't install illuminate/notifications v5.3.0|don't install laravel/framework v5.6.27
    - don't install illuminate/notifications v5.3.16|don't install laravel/framework v5.6.27
    - don't install illuminate/notifications v5.3.23|don't install laravel/framework v5.6.27
    - don't install illuminate/notifications v5.3.4|don't install laravel/framework v5.6.27
    - Installation request for laravel/framework (locked at v5.6.27, required as 5.6.*) -> satisfiable by laravel/framework[v5.6.27].

**Comment by atymic** [comment]
PR here: https://github.com/laravel-notification-channels/trello/pull/13

Release will be tagged shortly.
