### ISSUE TITLE
Support for laravel 5.5 and 5.6

### ISSUE THREAD

**Issue by KevinFairbanks** [laravel-notification-channels/trello#12]
Can you add the support for the latest versions?

**Comment by KevinFairbanks** [comment]
Since there has been no response from the maintainer/developer I have made a working copy with support for 5.5 and 5.6 at https://github.com/PinkTie/laravel-notifications-trello

**Comment by atymic** [comment]
PR here: https://github.com/laravel-notification-channels/trello/pull/13

Release will be tagged shortly.
